import type { Metadata } from "next";
import "./globals.css";
import SessionProvider from "@/components/SessionProvider";
import QueryClientProvider from "@/components/QueryClientProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <SessionProvider>
          <QueryClientProvider>
            <div className="page-frame">{children}</div>
          </QueryClientProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
